name: Create a comment on new issues
on:
  issues:
    types: [opened]
jobs:
  comment-with-actions:
    runs-on: ubuntu-latest
    steps:
      - name: "Dump github context"
        run: echo '${{ toJSON(github.event) }}' | jq
        shell: bash
